"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "sonner";
import MemberForm from "@/components/admin/members/MemberForm";
import MemberImport from "@/components/admin/members/MemberImport";
import MemberModal from "@/components/admin/members/MemberModal";
import MemberTable from "@/components/admin/members/MemberTable";
import { createMember, deleteMember, exportMembers, getMembers, updateMember } from "@/services/member.service";
import type { Member, MemberFormData } from "@/types/member";

export default function AdminOfficeBearersPage() { const [search, setSearch] = useState(""); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Member | null>(null); const [viewing, setViewing] = useState<Member | null>(null); const client = useQueryClient(); const { data, isLoading } = useQuery({ queryKey: ["members", "admin", search], queryFn: () => getMembers(1, 50, search) }); const refresh = () => client.invalidateQueries({ queryKey: ["members"] }); const save = async (form: MemberFormData) => { try { if (editing) await updateMember(editing._id, form); else await createMember(form); toast.success(editing ? "Member updated." : "Member added."); setEditing(null); setFormOpen(false); await refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save member."); } }; const remove = async (member: Member) => { if (!window.confirm(`Delete ${member.fullName}?`)) return; try { await deleteMember(member._id); toast.success("Member deleted."); await refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to delete member."); } }; return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Office Bearers</h1><p className="text-slate-500">Manage press club office bearers.</p></div><div className="flex gap-3"><button onClick={() => { setEditing(null); setFormOpen(true); }} className="rounded-lg bg-blue-700 px-4 py-2.5 font-semibold text-white">Add Office Bearer</button><button onClick={() => void exportMembers("xlsx")} className="rounded-lg bg-emerald-600 px-4 py-2.5 font-semibold text-white">Export Excel</button><button onClick={() => void exportMembers("csv")} className="rounded-lg border px-4 py-2.5 font-semibold">Export CSV</button></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-white p-5 shadow"><p className="text-sm text-slate-500">Total Office Bearers</p><p className="mt-1 text-3xl font-bold">{data?.stats?.total ?? 0}</p></div><div className="rounded-xl bg-white p-5 shadow"><p className="text-sm text-slate-500">Active Office Bearers</p><p className="mt-1 text-3xl font-bold">{data?.stats?.active ?? 0}</p></div></div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, email, phone, or designation" className="w-full max-w-xl rounded-lg border p-3" />{formOpen && <MemberForm member={editing} onSubmit={save} onCancel={() => { setEditing(null); setFormOpen(false); }} />}<MemberImport onComplete={refresh} />{isLoading ? <p className="py-10 text-center text-slate-500">Loading office bearers...</p> : <MemberTable members={data?.data || []} onView={setViewing} onEdit={(member) => { setEditing(member); setFormOpen(true); }} onDelete={remove} />}<MemberModal member={viewing} onClose={() => setViewing(null)} /></div>; }
