import type { ImportSummary, Member, MemberFormData, MemberListResponse } from "@/types/member";

const API = `${process.env.NEXT_PUBLIC_API_URL}/members`;
const auth = () => ({ Authorization: `Bearer ${typeof window !== "undefined" ? localStorage.getItem("token") || "" : ""}` });
const request = async <T>(url: string, options?: RequestInit): Promise<T> => { const response = await fetch(url, options); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message || "Member request failed."); return payload.data as T; };
const toForm = (data: MemberFormData) => { const form = new FormData(); form.append("fullName", data.fullName); form.append("email", data.email || ""); form.append("phone", data.phone || ""); form.append("designation", data.designation || ""); form.append("organization", data.organization || ""); form.append("state", data.state || ""); form.append("district", data.district || ""); form.append("displayOrder", String(data.displayOrder)); if (data.photo) form.append("photo", data.photo); return form; };

export type MemberDirectoryFilters = { search?: string; organization?: string; designation?: string; state?: string; district?: string; sort?: "az" | "za" | "recent" };
export const getPublicMembers = async (page = 1, limit = 12, filters: MemberDirectoryFilters = {}, all = false): Promise<MemberListResponse> => { const params = new URLSearchParams({ page: String(page), limit: String(limit) }); if (all) params.set("all", "true"); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value); }); const response = await fetch(`${API}/public?${params}`); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message || "Unable to load office bearers."); return { data: payload.data, pagination: payload.pagination, stats: payload.stats }; };
export const getMembers = async (page = 1, limit = 10, search = ""): Promise<MemberListResponse> => { const params = new URLSearchParams({ page: String(page), limit: String(limit) }); if (search) params.set("search", search); const response = await fetch(`${API}?${params}`, { headers: auth() }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message || "Unable to load members."); return { data: payload.data, pagination: payload.pagination, stats: payload.stats }; };
export const getMember = (id: string) => request<Member>(`${API}/${id}`);
export const createMember = (data: MemberFormData) => request<Member>(API, { method: "POST", headers: auth(), body: toForm(data) });
export const updateMember = (id: string, data: MemberFormData) => request<Member>(`${API}/${id}`, { method: "PUT", headers: auth(), body: toForm(data) });
export const deleteMember = (id: string) => request<unknown>(`${API}/${id}`, { method: "DELETE", headers: auth() });
export const importMembers = (file: File) => { const form = new FormData(); form.append("file", file); return request<ImportSummary>(`${API}/import`, { method: "POST", headers: auth(), body: form }); };
export const exportMembers = async (format: "xlsx" | "csv") => { const response = await fetch(`${API}/export?format=${format}`, { headers: auth() }); if (!response.ok) throw new Error("Failed to export members."); const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = `members.${format}`; link.click(); URL.revokeObjectURL(url); };
