import { Request, Response } from "express";
import * as XLSX from "xlsx";
import Member from "../models/Member";
import cloudinary from "../config/cloudinary";
import { deleteCloudinaryAssets } from "../utils/cloudinaryCleanup";

const defaultPhoto = "/images/members/default.png";
const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
const payload = (body: Request["body"]) => ({ fullName: text(body.fullName), email: text(body.email), phone: text(body.phone), designation: text(body.designation), organization: text(body.organization), state: text(body.state), district: text(body.district), displayOrder: Number(body.displayOrder ?? 0) });
const valid = (member: ReturnType<typeof payload>) => Boolean(member.fullName) && (!member.email || /^\S+@\S+\.\S+$/.test(member.email)) && Number.isInteger(member.displayOrder) && member.displayOrder >= 0;
const uploadPhoto = async (file?: Express.Multer.File) => file ? (await cloudinary.uploader.upload(`data:${file.mimetype};base64,${file.buffer.toString("base64")}`, { folder: "members" })).secure_url : undefined;
const filters = (query: Request["query"]) => { const search = text(query.search); const filter: Record<string, unknown> = {}; if (search) filter.$or = ["fullName", "email", "designation", "organization"].map((field) => ({ [field]: { $regex: search, $options: "i" } })); (["organization", "designation", "state", "district"] as const).forEach((field) => { const value = text(query[field]); if (value) filter[field] = { $regex: value, $options: "i" }; }); return filter; };

export const getMembers = async (req: Request, res: Response) => { try { const page = Math.max(Number(req.query.page) || 1, 1); const requestedAll = req.query.all === "true"; const limit = requestedAll ? 0 : Math.min(Math.max(Number(req.query.limit) || 10, 1), 100); const filter = filters(req.query); const sort = req.query.sort === "az" ? "fullName" : req.query.sort === "za" ? "-fullName" : "displayOrder createdAt"; const query = Member.find(filter).sort(sort); if (!requestedAll) query.skip((page - 1) * limit).limit(limit); const [data, total, statsTotal] = await Promise.all([query, Member.countDocuments(filter), Member.countDocuments()]); res.json({ success: true, data, pagination: { page, limit: requestedAll ? total : limit, total, pages: requestedAll ? 1 : Math.max(Math.ceil(total / limit), 1) }, stats: { total: statsTotal, active: statsTotal } }); } catch { res.status(500).json({ success: false, message: "Failed to fetch members." }); } };
export const getPublicMembers = async (req: Request, res: Response) => getMembers(req, res);
export const getMember = async (req: Request, res: Response) => { try { const data = await Member.findById(req.params.id); return data ? res.json({ success: true, data }) : res.status(404).json({ success: false, message: "Member not found." }); } catch { return res.status(400).json({ success: false, message: "Invalid member id." }); } };
export const createMember = async (req: Request, res: Response) => { try { const member = payload(req.body); if (!valid(member)) return res.status(400).json({ success: false, message: "Full Name, a valid email when provided, and a non-negative display order are required." }); const photo = await uploadPhoto(req.file); if (!photo) return res.status(400).json({ success: false, message: "A member photo is required." }); const data = await Member.create({ ...member, photo }); res.status(201).json({ success: true, data }); } catch { res.status(500).json({ success: false, message: "Failed to create member." }); } };
export const updateMember = async (req: Request, res: Response) => { try { const member = payload(req.body); if (!valid(member)) return res.status(400).json({ success: false, message: "Full Name, a valid email when provided, and a non-negative display order are required." }); const existing = await Member.findById(req.params.id); if (!existing) return res.status(404).json({ success: false, message: "Member not found." }); const photo = await uploadPhoto(req.file); const data = await Member.findByIdAndUpdate(req.params.id, { ...member, ...(photo ? { photo } : {}) }, { returnDocument: "after", runValidators: true }); if (photo && existing.photo !== defaultPhoto && existing.photo !== photo) await deleteCloudinaryAssets([existing.photo]); res.json({ success: true, data }); } catch { res.status(500).json({ success: false, message: "Failed to update member." }); } };
export const deleteMember = async (req: Request, res: Response) => { try { const data = await Member.findByIdAndDelete(req.params.id); if (!data) return res.status(404).json({ success: false, message: "Member not found." }); if (data.photo !== defaultPhoto) await deleteCloudinaryAssets([data.photo]); return res.json({ success: true, message: "Member deleted." }); } catch { return res.status(400).json({ success: false, message: "Invalid member id." }); } };
export const importMembers = async (req: Request, res: Response) => { if (!req.file) return res.status(400).json({ success: false, message: "Upload an .xlsx, .xls, or .csv file." }); try { const workbook = XLSX.read(req.file.buffer, { type: "buffer" }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" }); const validRows: Array<Record<string, string | number>> = []; const failedRows: Array<{ row: number; reason: string }> = []; rows.forEach((row, index) => { const member = { fullName: text(row["Full Name"] || row.fullName), email: text(row.Email || row.email), phone: text(row.Phone || row.phone), designation: text(row.Designation || row.designation), organization: text(row.Organization || row.organization), state: text(row.State || row.state), district: text(row.District || row.district), displayOrder: Number(row["Display Order"] ?? row.displayOrder ?? 0), photo: text(row["Photo URL"] || row.photo || row.photoUrl) || defaultPhoto }; if (!valid(member)) failedRows.push({ row: index + 2, reason: "Full Name, a valid email when provided, and a non-negative display order are required." }); else validRows.push(member); }); if (validRows.length) await Member.insertMany(validRows, { ordered: false }); res.json({ success: true, data: { totalRows: rows.length, imported: validRows.length, failed: failedRows.length, failedRows } }); } catch { res.status(400).json({ success: false, message: "Unable to read the import file." }); } };
export const exportMembers = async (req: Request, res: Response) => { try { const data = await Member.find(filters(req.query)).sort({ displayOrder: 1, createdAt: 1 }).lean(); const rows = data.map((member) => ({ "Full Name": member.fullName, Email: member.email || "", Phone: member.phone || "", Designation: member.designation || "", Organization: member.organization || "", State: member.state || "", District: member.district || "", "Display Order": member.displayOrder ?? 0, "Photo URL": member.photo })); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), "Members"); const type = req.query.format === "csv" ? "csv" : "xlsx"; const content = XLSX.write(workbook, { type: "buffer", bookType: type }); res.setHeader("Content-Type", type === "csv" ? "text/csv" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); res.setHeader("Content-Disposition", `attachment; filename=members.${type}`); res.send(content); } catch { res.status(500).json({ success: false, message: "Failed to export members." }); } };
