import { Request, Response } from "express";
import * as XLSX from "xlsx";
import OfficeBearer from "../models/OfficeBearer";
import cloudinary from "../config/cloudinary";
import { deleteCloudinaryAssets } from "../utils/cloudinaryCleanup";

const defaultPhoto = "/images/members/default.png";
const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
const payload = (body: Request["body"]) => ({ fullName: text(body.fullName), email: text(body.email), phone: text(body.phone), designation: text(body.designation), organization: text(body.organization), state: text(body.state), district: text(body.district), displayOrder: Number(body.displayOrder ?? 0) });
const valid = (officeBearer: ReturnType<typeof payload>) => Boolean(officeBearer.fullName) && (!officeBearer.email || /^\S+@\S+\.\S+$/.test(officeBearer.email)) && Number.isInteger(officeBearer.displayOrder) && officeBearer.displayOrder >= 0;
const uploadPhoto = async (file?: Express.Multer.File) => file ? (await cloudinary.uploader.upload(`data:${file.mimetype};base64,${file.buffer.toString("base64")}`, { folder: "office-bearers" })).secure_url : undefined;
const filters = (query: Request["query"]) => { const search = text(query.search); const filter: Record<string, unknown> = {}; if (search) filter.$or = ["fullName", "email", "designation", "organization"].map((field) => ({ [field]: { $regex: search, $options: "i" } })); (["organization", "designation", "state", "district"] as const).forEach((field) => { const value = text(query[field]); if (value) filter[field] = { $regex: value, $options: "i" }; }); return filter; };

export const getOfficeBearers = async (req: Request, res: Response) => { try { const page = Math.max(Number(req.query.page) || 1, 1); const requestedAll = req.query.all === "true"; const limit = requestedAll ? 0 : Math.min(Math.max(Number(req.query.limit) || 10, 1), 100); const filter = filters(req.query); const sort = req.query.sort === "az" ? "fullName" : req.query.sort === "za" ? "-fullName" : "displayOrder createdAt"; const query = OfficeBearer.find(filter).sort(sort); if (!requestedAll) query.skip((page - 1) * limit).limit(limit); const [data, total, statsTotal] = await Promise.all([query, OfficeBearer.countDocuments(filter), OfficeBearer.countDocuments()]); res.json({ success: true, data, pagination: { page, limit: requestedAll ? total : limit, total, pages: requestedAll ? 1 : Math.max(Math.ceil(total / limit), 1) }, stats: { total: statsTotal, active: statsTotal } }); } catch { res.status(500).json({ success: false, message: "Failed to fetch office bearers." }); } };
export const getPublicOfficeBearers = async (req: Request, res: Response) => getOfficeBearers(req, res);
export const getOfficeBearer = async (req: Request, res: Response) => { try { const data = await OfficeBearer.findById(req.params.id); return data ? res.json({ success: true, data }) : res.status(404).json({ success: false, message: "Office bearer not found." }); } catch { return res.status(400).json({ success: false, message: "Invalid office bearer id." }); } };
export const createOfficeBearer = async (req: Request, res: Response) => { try { const officeBearer = payload(req.body); if (!valid(officeBearer)) return res.status(400).json({ success: false, message: "Full Name, a valid email when provided, and a non-negative display order are required." }); const photo = await uploadPhoto(req.file); if (!photo) return res.status(400).json({ success: false, message: "An office bearer photo is required." }); const data = await OfficeBearer.create({ ...officeBearer, photo }); res.status(201).json({ success: true, data }); } catch { res.status(500).json({ success: false, message: "Failed to create office bearer." }); } };
export const updateOfficeBearer = async (req: Request, res: Response) => { try { const officeBearer = payload(req.body); if (!valid(officeBearer)) return res.status(400).json({ success: false, message: "Full Name, a valid email when provided, and a non-negative display order are required." }); const existing = await OfficeBearer.findById(req.params.id); if (!existing) return res.status(404).json({ success: false, message: "Office bearer not found." }); const photo = await uploadPhoto(req.file); const data = await OfficeBearer.findByIdAndUpdate(req.params.id, { ...officeBearer, ...(photo ? { photo } : {}) }, { returnDocument: "after", runValidators: true }); if (photo && existing.photo !== defaultPhoto && existing.photo !== photo) await deleteCloudinaryAssets([existing.photo]); res.json({ success: true, data }); } catch { res.status(500).json({ success: false, message: "Failed to update office bearer." }); } };
export const deleteOfficeBearer = async (req: Request, res: Response) => { try { const data = await OfficeBearer.findByIdAndDelete(req.params.id); if (!data) return res.status(404).json({ success: false, message: "Office bearer not found." }); if (data.photo !== defaultPhoto) await deleteCloudinaryAssets([data.photo]); return res.json({ success: true, message: "Office bearer deleted." }); } catch { return res.status(400).json({ success: false, message: "Invalid office bearer id." }); } };
export const importOfficeBearers = async (req: Request, res: Response) => { if (!req.file) return res.status(400).json({ success: false, message: "Upload an .xlsx, .xls, or .csv file." }); try { const workbook = XLSX.read(req.file.buffer, { type: "buffer" }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" }); const validRows: Array<Record<string, string | number>> = []; const failedRows: Array<{ row: number; reason: string }> = []; rows.forEach((row, index) => { const officeBearer = { fullName: text(row["Full Name"] || row.fullName), email: text(row.Email || row.email), phone: text(row.Phone || row.phone), designation: text(row.Designation || row.designation), organization: text(row.Organization || row.organization), state: text(row.State || row.state), district: text(row.District || row.district), displayOrder: Number(row["Display Order"] ?? row.displayOrder ?? 0), photo: text(row["Photo URL"] || row.photo || row.photoUrl) || defaultPhoto }; if (!valid(officeBearer)) failedRows.push({ row: index + 2, reason: "Full Name, a valid email when provided, and a non-negative display order are required." }); else validRows.push(officeBearer); }); if (validRows.length) await OfficeBearer.insertMany(validRows, { ordered: false }); res.json({ success: true, data: { totalRows: rows.length, imported: validRows.length, failed: failedRows.length, failedRows } }); } catch { res.status(400).json({ success: false, message: "Unable to read the import file." }); } };
export const exportOfficeBearers = async (req: Request, res: Response) => { try { const data = await OfficeBearer.find(filters(req.query)).sort({ displayOrder: 1, createdAt: 1 }).lean(); const rows = data.map((officeBearer) => ({ "Full Name": officeBearer.fullName, Email: officeBearer.email || "", Phone: officeBearer.phone || "", Designation: officeBearer.designation || "", Organization: officeBearer.organization || "", State: officeBearer.state || "", District: officeBearer.district || "", "Display Order": officeBearer.displayOrder ?? 0, "Photo URL": officeBearer.photo })); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), "Office Bearers"); const type = req.query.format === "csv" ? "csv" : "xlsx"; const content = XLSX.write(workbook, { type: "buffer", bookType: type }); res.setHeader("Content-Type", type === "csv" ? "text/csv" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); res.setHeader("Content-Disposition", `attachment; filename=office-bearers.${type}`); res.send(content); } catch { res.status(500).json({ success: false, message: "Failed to export office bearers." }); } };
